services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    environment:
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY:?}
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_URL: https://paperless.${TRAEFIK_DOMAIN:?}
      PAPERLESS_REDIS: redis://cache:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPASS: ${DB_PASS:?}
      PAPERLESS_ADMIN_USER: ${ADMIN_USER:?}
      PAPERLESS_ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}
      USERMAP_UID: ${UID:?}
      USERMAP_GID: ${GID:?}
      PAPERLESS_EMAIL_HOST: ${EMAIL_HOST:?}
      PAPERLESS_EMAIL_PORT: ${EMAIL_PORT:?}
      PAPERLESS_EMAIL_USE_TLS: ${EMAIL_USE_TLS:?}
      PAPERLESS_EMAIL_USE_SSL: ${EMAIL_USE_SSL:?}
      PAPERLESS_EMAIL_HOST_USER: ${EMAIL_USER:?}
      PAPERLESS_EMAIL_HOST_PASSWORD: ${EMAIL_PASSWORD:?}
      PAPERLESS_FILENAME_FORMAT: ${PAPERLESS_FILENAME_FORMAT}
      PAPERLESS_SOCIAL_ACCOUNT_DEFAULT_GROUPS: ${PAPERLESS_DEFAULT_GROUPS:-Basic}
      PAPERLESS_APP_TITLE: Paperless
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: true
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME

      # SSO settings
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "OAUTH_PKCE_ENABLED": true,
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik SSO",
                "client_id": "${AUTHENTIK_CLIENT_ID:?}",
                "secret": "${AUTHENTIK_SECRET:?}",
                "settings": {
                  "server_url": "https://auth.${TRAEFIK_DOMAIN:?}/application/o/paperless/.well-known/openid-configuration",
                  "fetch_userinfo": true
                }
              }
            ],
            "SCOPE": ["openid", "profile", "email"]
          }
        }
      PAPERLESS_LOGOUT_REDIRECT_URL: https://auth.${TRAEFIK_DOMAIN:?}/application/o/paperless/end-session/"
      PAPERLESS_SOCIAL_AUTO_SIGNUP: false
      PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: true
      PAPERLESS_DISABLE_REGULAR_LOGIN: false
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: false
    labels:
      - traefik.enable=true
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - traefik.http.routers.paperless.rule=Host(`paperless.${TRAEFIK_DOMAIN:?}`)
      - traefik.http.routers.paperless.entrypoints=websecure
      - traefik.http.routers.paperless.middlewares=authentik@file
    networks:
      - paperless
      - traefik
    ports:
      - 8000:8000
    volumes:
      - ${DATA_DIR:?}/data:/usr/src/paperless/data
      - ${DATA_DIR:?}/media:/usr/src/paperless/media
      - ${DATA_DIR:?}/export:/usr/src/paperless/export
      - ${DATA_DIR:?}/consume:/usr/src/paperless/consume
    depends_on:
      - cache
      - db

  cache:
    image: valkey/valkey:8.1.2-alpine
    container_name: paperless-cache
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - cache:/data

  db:
    image: docker.io/library/postgres:18
    container_name: paperless-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${DB_PASS:?}
      TZ: ${TZ}
    networks:
      - paperless
    volumes:
      - ${DB_DIR:?}:/var/lib/postgresql

networks:
  paperless:
    name: paperless
  traefik:
    external: true

volumes:
  cache:
    name: paperless-cache